from langchain.agents import create_agent
from langchain.messages import (
    HumanMessage,
    AIMessage,
    SystemMessage
)
from src.model import get_model
from src.tools import get_tools

# -----------------------
# Agent setup
# -----------------------

llm = get_model(2000)
tools = [get_tools()[2]]

agent = create_agent(
    llm,
    system_prompt=SystemMessage("""You are a reasoning AI agent.

You will be given:
1) A previous context summary
2) The current user query
3) The AI response generated by another agent

Your task is to merge all relevant information into a single updated summarized context for another model to use.

RULES:
- Preserve all important facts, decisions, constraints, and clarifications.
- (IMPORTANT) DO NOT LOSE CONTEXT.
- (IMPORTANT) NEVER LOSE DATA RELATED TO USER. ALSO, PII IS IMPORTANT.
- (IMPORTANT) Do NOT introduce new assumptions or interpretations.
- (IMPORTANT) Do NOT add analysis, explanations, or metadata.
- If removal is necessary due to size limits then, remove older, obsolete, or no-longer-relevant context first.
- Resolve redundancies by merging overlapping information rather than deleting it.
- Produce a clear and detailed AI Agent readable response.

OUTPUT REQUIREMENTS:
- (IMPORTANT) Return ONLY the final summarized context as a plain string.
- Do NOT include labels, formatting, or commentary.
- (IMPORTANT) Ensure the summary remains coherent, self-contained, and usable as future context.
- (IMPORTANT) The produced output can be large, upto 2000 characters.
- The summarized context MUST NOT exceed 2000 characters.
""")
)


# -----------------------
# Helper Function
# -----------------------

def summarize(context, user_query, ai_response):
    messages = []
    messages.append(HumanMessage(f"PREVIOUS CONTEXT: {context}\n\nCURRENT USER QUERY: {user_query}\n\nOTHER AGENT RESPONSE: {ai_response}"))
    response = agent.invoke({"messages": messages})

    for msg in response["messages"]:
        if isinstance(msg, AIMessage):
            final_answer = msg.content

    res = final_answer.split("</think>")
    final_answer = res[1] if len(res) == 2 else res[0]
    return final_answer